In [1]:
import numpy as np
from scipy.linalg import toeplitz
from CD import CD_non_separable
from Forward_CV import Forward_CV

In [2]:
N=100
P=1000
Corr=0.5**toeplitz(np.arange(0,P),np.arange(0,P))
beta=np.zeros((P,1))
beta[0]=3
beta[1]=1.5
beta[4]=2
beta[9]=1
beta[12]=1
beta[18]=0.5
beta[25]=-0.5
beta[30]=2.0
beta[45]=-1.2
beta[50]=-1
sigma=1
X=np.random.multivariate_normal(np.zeros(P), Corr, N)
Y=X@beta+sigma*np.random.randn(N,1)

In [3]:
beta_estimator,sparsity,sigma2_estimator=CD_non_separable(Y,X,C=2,s=3)

In [4]:
np.where(beta_estimator!=0)

(array([ 0,  1,  4,  9, 12, 30, 45, 50]), array([0, 0, 0, 0, 0, 0, 0, 0]))

In [5]:
beta_estimator[np.where(beta_estimator!=0)]

array([ 2.89362136,  1.73529452,  2.18861813,  1.0619909 ,  0.88048215,
        1.8453936 , -0.92618697, -1.14624847])

In [6]:
beta_estimator_cv,sparsity_cv,sigma2_estimator_cv=Forward_CV(Y,X)

In [7]:
np.where(beta_estimator_cv!=0)

(array([ 0,  1,  4,  9, 12, 30, 45, 50]), array([0, 0, 0, 0, 0, 0, 0, 0]))

In [8]:
beta_estimator_cv[np.where(beta_estimator_cv!=0)]

array([ 2.90120046,  1.6848821 ,  2.16013493,  1.0084577 ,  0.83855872,
        1.80805594, -0.84886758, -1.08570265])