In [1]:
import numpy as np
from scipy.linalg import toeplitz
from CD import CD_non_separable

In [2]:
N=300
P=3000
Corr=0.5**toeplitz(np.arange(0,P),np.arange(0,P))
beta=np.zeros((P,1))
beta[0]=3
beta[1]=1.5
beta[4]=2
beta[9]=1
beta[12]=1
beta[18]=0.5
beta[25]=-0.5
beta[30]=2.0
beta[45]=-1.2
beta[50]=-1
sigma=1
X=np.random.multivariate_normal(np.zeros(P), Corr, N)
Y=X@beta+sigma*np.random.randn(N,1)

In [3]:
beta_estimator,sparsity,sigma2_estimator=CD_non_separable(Y,X,C=3,s=1)

In [7]:
beta_estimator[beta!=0]

array([ 2.99744978,  1.43137168,  1.9632831 ,  0.94975718,  0.89648737,
        0.40138038, -0.40164123,  1.90238069, -1.16072118, -0.89469055])

In [8]:
beta_estimator[beta_estimator!=0]

array([ 2.99744978,  1.43137168,  1.9632831 ,  0.94975718,  0.89648737,
        0.40138038, -0.40164123,  1.90238069, -1.16072118, -0.89469055])

In [9]:
sparsity

10

In [10]:
sigma2_estimator

array([[1.17044651]])