In [88]:
import numpy as np
from scipy.linalg import toeplitz
from CD import CD_non_separable

In [89]:
N=100
P=1000
Corr=0.5**toeplitz(np.arange(0,P),np.arange(0,P))
beta=np.zeros((P,1))
beta[0]=3
beta[1]=1.5
beta[4]=2
beta[9]=1
beta[12]=1
beta[18]=0.5
beta[25]=-0.5
beta[30]=2.0
beta[45]=-1.2
beta[50]=-1
sigma=1
X=np.random.multivariate_normal(np.zeros(P), Corr, N)
Y=X@beta+sigma*np.random.randn(N,1)

In [90]:
beta_estimator,sparsity,sigma2_estimator=CD_non_separable(Y,X,C=1,s=1)

In [91]:
beta_estimator[beta!=0]

array([ 2.9752717 ,  1.45798051,  1.88526668,  1.12045913,  0.98286524,
        0.47753977, -0.49107225,  1.98033515, -1.04466528, -0.87991188])

In [92]:
beta_estimator[beta_estimator!=0]

array([ 2.9752717 ,  1.45798051,  1.88526668,  1.12045913,  0.98286524,
        0.47753977, -0.49107225,  1.98033515, -1.04466528, -0.87991188,
       -0.14336356])

In [93]:
sparsity

11

In [94]:
sigma2_estimator

array([[0.82350402]])