In [1]:
import numpy as np
from scipy.linalg import toeplitz
from CD import CD_non_separable

In [2]:
N=500
P=5000
Corr=0.5**toeplitz(np.arange(0,P),np.arange(0,P))
beta=np.zeros((P,1))
beta[0]=3
beta[1]=1.5
beta[4]=2
beta[9]=1
beta[12]=1
beta[18]=0.5
beta[25]=-0.5
beta[30]=2.0
beta[45]=-1.2
beta[50]=-1
sigma=1
X=np.random.multivariate_normal(np.zeros(P), Corr, N)
Y=X@beta+sigma*np.random.randn(N,1)

In [3]:
beta_estimator,sparsity,sigma2_estimator=CD_non_separable(Y,X,C=1,s=2)

In [4]:
beta_estimator[beta!=0]

array([ 3.1167825 ,  1.37764691,  1.97208455,  0.98953175,  0.95600373,
        0.44197157, -0.4649767 ,  1.97368495, -1.1554335 , -1.00676787])

In [5]:
beta_estimator[beta_estimator!=0]

array([ 3.1167825 ,  1.37764691,  1.97208455,  0.98953175,  0.95600373,
        0.44197157, -0.4649767 ,  1.97368495, -1.1554335 , -1.00676787])

In [6]:
sparsity

10

In [7]:
sigma2_estimator

array([[1.04050812]])